version: "3.8"
services:
  stad-spring:
    image: stad-spring-image
    container_name: stad-spring
    ports:
      - "18080:8080"
    networks:
      - ubuntu_my-network
    restart: unless-stopped 
    
  stad-alert:
    image: stad-alert-image
    container_name: stad-alert
    ports:
      - "18081:8080"
    networks:
      - ubuntu_my-network
    restart: unless-stopped

  stad-stats:
    image: stad-stats-image
    container_name: stad-stats
    ports:
      - "18082:8080"
    networks:
      - ubuntu_my-network
    restart: unless-stopped 

  stad-stream:
    image: stad-stream-image
    container_name: stad-stream
    ports:
      - "18083:8080"
    networks:
      - ubuntu_my-network
    restart: unless-stopped 

  stad-react:
    image: stad-react-image
    container_name: stad-react
    ports:
      - "3000:3000"
    restart: unless-stopped 

networks:
  ubuntu_my-network:
    external: true
    name: ubuntu_my-network