cloud:
  aws:
    bucket: ssafy-stad
    region:
      static: ap-northeast-2
    stack:
      auto: false
#     EC2에서 Spring Cloud 프로젝트를 실행시키면 기본으로 CloudFormation 구성을 시작합니다.
#     설정한 CloudFormation이 없으면 프로젝트 시작이 안되니, 해당 내용을 사용하지 않도록 false를 등록합니다.
spring:
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB