spring:
  config:
    activate:
      on-profile: dev
  kafka:
    bootstrap-servers: localhost:10002
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    bootstrap-servers: kafka-1:10001
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer