export const SelectAdMainCategory = [
  { value: "A", label: "가구/인테리어" },
  { value: "B", label: "도서" },
  { value: "C", label: "디지털/가전" },
  { value: "D", label: "생활/건강" },
  { value: "E", label: "스포츠/레저" },
  { value: "F", label: "식품" },
  { value: "G", label: "여가/생활편의" },
  { value: "H", label: "출산/육아" },
  { value: "I", label: "패션의류" },
  { value: "J", label: "패션잡화" },
  { value: "K", label: "화장품/미용" },
];
interface subCategoryType {
  [key: string]: { value: string; label: string }[];
}
export const SelectAdSubCategory: subCategoryType = {
  A: [
    { value: "AA016", label: "DIY자재/용품" },
    { value: "AA015", label: "거실가구" },
    { value: "AA014", label: "서재/사무용가구" },
    { value: "AA013", label: "솜류" },
    { value: "AA012", label: "수납가구" },
    { value: "AA011", label: "수예" },
    { value: "AA010", label: "아동/주니어가구" },
    { value: "AA009", label: "아웃도어가구" },
    { value: "AA008", label: "인테리어소품" },
    { value: "AA007", label: "주방가구" },
    { value: "AA006", label: "침구단품" },
    { value: "AA005", label: "침구세트" },
    { value: "AA004", label: "침실가구" },
    { value: "AA003", label: "카페트/러그" },
    { value: "AA002", label: "커튼/블라인드" },
    { value: "AA001", label: "홈데코" },
  ],
  B: [
    { value: "BB026", label: "가정/요리" },
    { value: "BB025", label: "건강/취미" },
    { value: "BB024", label: "경제/경영" },
    { value: "BB023", label: "고등학교 참고서" },
    { value: "BB022", label: "국어/외국어" },
    { value: "BB021", label: "만화" },
    { value: "BB020", label: "사회/정치" },
    { value: "BB019", label: "소설" },
    { value: "BB018", label: "수험서/자격증" },
    { value: "BB017", label: "시/에세이" },
    { value: "BB016", label: "어린이" },
    { value: "BB015", label: "여행" },
    { value: "BB014", label: "역사" },
    { value: "BB013", label: "예술/대중문화" },
    { value: "BB012", label: "외국도서" },
    { value: "BB011", label: "유아" },
    { value: "BB010", label: "인문" },
    { value: "BB009", label: "자기계발" },
    { value: "BB008", label: "자연/과학" },
    { value: "BB007", label: "잡지" },
    { value: "BB006", label: "종교" },
    { value: "BB005", label: "중고도서" },
    { value: "BB004", label: "중학교 참고서" },
    { value: "BB003", label: "청소년" },
    { value: "BB002", label: "초등학교 참고서" },
    { value: "BB001", label: "컴퓨터/IT" },
  ],
  C: [
    { value: "CC027", label: "PC" },
    { value: "CC026", label: "PC부품" },
    { value: "CC025", label: "PC액세서리" },
    { value: "CC024", label: "게임기/타이틀" },
    { value: "CC023", label: "계절가전" },
    { value: "CC022", label: "광학기기/용품" },
    { value: "CC021", label: "네트워크장비" },
    { value: "CC020", label: "노트북" },
    { value: "CC019", label: "노트북액세서리" },
    { value: "CC018", label: "멀티미디어장비" },
    { value: "CC017", label: "모니터" },
    { value: "CC016", label: "모니터주변기기" },
    { value: "CC015", label: "생활가전" },
    { value: "CC014", label: "소프트웨어" },
    { value: "CC013", label: "영상가전" },
    { value: "CC012", label: "음향가전" },
    { value: "CC011", label: "이미용가전" },
    { value: "CC010", label: "자동차기기" },
    { value: "CC009", label: "저장장치" },
    { value: "CC008", label: "주방가전" },
    { value: "CC007", label: "주변기기" },
    { value: "CC006", label: "카메라/캠코더용품" },
    { value: "CC005", label: "태블릿PC" },
    { value: "CC004", label: "태블릿PC액세서리" },
    { value: "CC003", label: "학습기기" },
    { value: "CC002", label: "휴대폰" },
    { value: "CC001", label: "휴대폰액세서리" },
  ],
  D: [
    { value: "DD001", label: "DVD" },
    { value: "DD002", label: "건강관리용품" },
    { value: "DD003", label: "건강측정용품" },
    { value: "DD004", label: "공구" },
    { value: "DD005", label: "관상어용품" },
    { value: "DD006", label: "구강위생용품" },
    { value: "DD007", label: "냉온/찜질용품" },
    { value: "DD008", label: "눈건강용품" },
    { value: "DD009", label: "당뇨관리용품" },
    { value: "DD010", label: "문구/사무용품" },
    { value: "DD011", label: "물리치료/저주파용품" },
    { value: "DD012", label: "반려동물" },
    { value: "DD013", label: "발건강용품" },
    { value: "DD014", label: "블루레이" },
    { value: "DD015", label: "생활용품" },
    { value: "DD016", label: "세탁용품" },
    { value: "DD017", label: "수납/정리용품" },
    { value: "DD018", label: "수집품" },
    { value: "DD019", label: "실버용품" },
    { value: "DD020", label: "악기" },
    { value: "DD021", label: "안마용품" },
    { value: "DD022", label: "욕실용품" },
    { value: "DD023", label: "원예/식물" },
    { value: "DD024", label: "음반" },
    { value: "DD025", label: "의료용품" },
    { value: "DD026", label: "자동차용품" },
    { value: "DD027", label: "재활운동용품" },
    { value: "DD028", label: "정원/원예용품" },
    { value: "DD029", label: "종교" },
    { value: "DD030", label: "좌욕/좌훈용품" },
    { value: "DD031", label: "주방용품" },
    { value: "DD032", label: "청소용품" },
    { value: "DD033", label: "화방용품" },
  ],
  E: [
    { value: "EE001", label: "검도" },
    { value: "EE002", label: "골프" },
    { value: "EE003", label: "권투" },
    { value: "EE004", label: "기타스포츠용품" },
    { value: "EE005", label: "낚시" },
    { value: "EE006", label: "농구" },
    { value: "EE007", label: "당구용품" },
    { value: "EE008", label: "댄스" },
    { value: "EE009", label: "등산" },
    { value: "EE010", label: "마라톤용품" },
    { value: "EE011", label: "무술용품" },
    { value: "EE012", label: "배구" },
    { value: "EE013", label: "배드민턴" },
    { value: "EE014", label: "보호용품" },
    { value: "EE015", label: "볼링" },
    { value: "EE016", label: "수련용품" },
    { value: "EE017", label: "수영" },
    { value: "EE018", label: "스케이트/보드/롤러" },
    { value: "EE019", label: "스쿼시" },
    { value: "EE020", label: "스키/보드" },
    { value: "EE021", label: "스킨스쿠버" },
    { value: "EE022", label: "스포츠액세서리" },
    { value: "EE023", label: "야구" },
    { value: "EE024", label: "오토바이/스쿠터" },
    { value: "EE025", label: "요가/필라테스" },
    { value: "EE026", label: "인라인스케이트" },
    { value: "EE027", label: "자전거" },
    { value: "EE028", label: "족구" },
    { value: "EE029", label: "축구" },
    { value: "EE030", label: "캠핑" },
    { value: "EE031", label: "탁구" },
    { value: "EE032", label: "테니스" },
    { value: "EE033", label: "헬스" },
  ],
  F: [
    { value: "FF001", label: "가루/분말류" },
    { value: "FF002", label: "건강식품" },
    { value: "FF003", label: "과자/베이커리" },
    { value: "FF004", label: "김치" },
    { value: "FF005", label: "냉동/간편조리식품" },
    { value: "FF006", label: "농산물" },
    { value: "FF007", label: "다이어트식품" },
    { value: "FF008", label: "라면/면류" },
    { value: "FF009", label: "밀키트" },
    { value: "FF010", label: "반찬" },
    { value: "FF011", label: "소스/드레싱" },
    { value: "FF012", label: "수산물" },
    { value: "FF013", label: "식용유/오일" },
    { value: "FF014", label: "유가공품" },
    { value: "FF015", label: "음료" },
    { value: "FF016", label: "장류" },
    { value: "FF017", label: "잼/시럽" },
    { value: "FF018", label: "제과/제빵재료" },
    { value: "FF019", label: "조미료" },
    { value: "FF020", label: "주류" },
    { value: "FF021", label: "축산물" },
    { value: "FF022", label: "통조림/캔" },
  ],
  G: [
    { value: "GG001", label: "국내렌터카" },
    { value: "GG002", label: "국내여행/체험" },
    { value: "GG003", label: "생활편의" },
    { value: "GG004", label: "예체능레슨" },
    { value: "GG005", label: "원데이클래스" },
    { value: "GG006", label: "자기계발/취미 레슨" },
    { value: "GG007", label: "해외여행" },
    { value: "GG008", label: "홈케어서비스" },
  ],
  H: [
    { value: "HH001", label: "교구" },
    { value: "HH002", label: "구강청결용품" },
    { value: "HH003", label: "기저귀" },
    { value: "HH004", label: "목욕용품" },
    { value: "HH005", label: "물티슈" },
    { value: "HH006", label: "분유" },
    { value: "HH007", label: "소독/살균용품" },
    { value: "HH008", label: "수영복/용품" },
    { value: "HH009", label: "수유용품" },
    { value: "HH010", label: "스킨/바디용품" },
    { value: "HH011", label: "신생아의류" },
    { value: "HH012", label: "아기간식" },
    { value: "HH013", label: "안전용품" },
    { value: "HH014", label: "완구/매트" },
    { value: "HH015", label: "외출용품" },
    { value: "HH016", label: "위생/건강용품" },
    { value: "HH017", label: "유모차" },
    { value: "HH018", label: "유아가구" },
    { value: "HH019", label: "유아동 주얼리" },
    { value: "HH020", label: "유아동언더웨어/잠옷" },
    { value: "HH021", label: "유아동의류" },
    { value: "HH022", label: "유아동잡화" },
    { value: "HH023", label: "유아발육용품" },
    { value: "HH024", label: "유아세제" },
    { value: "HH025", label: "유아침구" },
    { value: "HH026", label: "이유식" },
    { value: "HH027", label: "이유식용품" },
    { value: "HH028", label: "인형" },
    { value: "HH029", label: "임부복" },
    { value: "HH030", label: "임산부용품" },
    { value: "HH031", label: "출산/돌기념품" },
    { value: "HH032", label: "카시트" },
  ],
  I: [
    { value: "II001", label: "남성언더웨어/잠옷" },
    { value: "II002", label: "남성의류" },
    { value: "II003", label: "여성언더웨어/잠옷" },
    { value: "II004", label: "여성의류" },
  ],
  J: [
    { value: "JJ001", label: "남성가방" },
    { value: "JJ002", label: "남성신발" },
    { value: "JJ003", label: "모자" },
    { value: "JJ004", label: "벨트" },
    { value: "JJ005", label: "선글라스/안경테" },
    { value: "JJ006", label: "순금" },
    { value: "JJ007", label: "시계" },
    { value: "JJ008", label: "신발용품" },
    { value: "JJ009", label: "양말" },
    { value: "JJ010", label: "여성가방" },
    { value: "JJ011", label: "여성신발" },
    { value: "JJ012", label: "여행용가방/소품" },
    { value: "JJ013", label: "장갑" },
    { value: "JJ014", label: "주얼리" },
    { value: "JJ015", label: "지갑" },
    { value: "JJ016", label: "패션소품" },
    { value: "JJ017", label: "헤어액세서리" },
  ],
  K: [
    { value: "KK001", label: "남성화장품" },
    { value: "KK002", label: "네일케어" },
    { value: "KK003", label: "마스크/팩" },
    { value: "KK004", label: "바디케어" },
    { value: "KK005", label: "베이스메이크업" },
    { value: "KK006", label: "뷰티소품" },
    { value: "KK007", label: "색조메이크업" },
    { value: "KK008", label: "선케어" },
    { value: "KK009", label: "스킨케어" },
    { value: "KK010", label: "클렌징" },
    { value: "KK011", label: "향수" },
    { value: "KK012", label: "헤어스타일링" },
    { value: "KK013", label: "헤어케어" },
  ],
};
