server:
  servlet:
    context-path: '/alert'
spring:
  profiles:
    group:
      default: dev
  config:
    import:
      - classpath:/db.yml
      - classpath:/msa.yml
      - classpath:/kafka.yml
      - classpath:/jpa.yml